---
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: tailr
    MYSQL_PASSWORD: tailr
    MYSQL_DATABASE: tailr
app:
  build: .
  environment:
    DATABASE_URL: "mysql://tailr:tailr@db/tailr"
    COOKIE_SECRET: "secret"
    GITHUB_CLIENT_ID: "eb2700d7dc16e8cc20ba"
    GITHUB_SECRET: "fcda22f4bf4f132c293a1e2b624ff6c43fb0e456"
    DEBUG: 1
  volumes:
    - .:/home/tailr/app
  ports:
    - "5000:5000"
  links:
    - db
