---
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: tailr
    MYSQL_PASSWORD: tailr
    MYSQL_DATABASE: tailr
app:
  build: .
  environment:
    DATABASE_URL: "mysql://tailr:tailr@db/tailr"
    COOKIE_SECRET: "secret"
    GITHUB_CLIENT_ID: "082fc14fead0c4ceed95"
    GITHUB_SECRET: "aacf422397aa3245ed71ad66dcc86ae6e1ff1e2f"
    DEBUG: 1
  volumes:
    - .:/home/tailr/app
  ports:
    - "5000:5000"
  links:
    - db
