---
# This role sets up the application database.

- name: ensure mariadb apt key is present
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0xcbcb082a1bb943db

- name: ensure mariadb apt repository is present
  apt_repository: repo="deb http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.0/ubuntu trusty main"

- name: ensure mariadb is installed
  apt: pkg=mariadb-server update_cache=yes

- name: ensure mariadb is running and enabled
  service: name=mysql state=started enabled=yes

- name: ensure mariadb python tools are installed
  apt: pkg=python-mysqldb state=present

- name: ensure application database is present
  mysql_db: name={{ db.name }} encoding=utf8 state=present

- name: ensure application database user is present
  mysql_user: name={{ db.user }} password={{ db.pass }} priv={{ db.name }}.*:ALL
