---
# This role sets up the project dependencies.

# OS

# - name: ensure application user account is present
#   user: name=tailr …

# - name: ensure appropriate number of open files per process are allowed
#   lineinfile: dest=/etc/security/limits.conf …

# Nginx

- name: ensure nginx is installed
  apt: pkg=nginx state=present

- name: ensure nginx default host is configured
  template: src=default.j2 dest=/etc/nginx/sites-available/default
  notify: reload nginx

- name: ensure nginx default host is enabled
  file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link
  notify: reload nginx

- name: ensure nginx is running and enabled
  service: name=nginx state=started enabled=yes

# Python

- name: ensure python-setuptools are installed
  apt: pkg=python-setuptools state=present

- name: ensure python-dev package is installed
  apt: pkg=python-dev state=present

- name: ensure pip is installed
  easy_install: name=pip

- name: ensure virtualenv is installed
  pip: name=virtualenv

# Dependencies

- name: ensure python-librdf is installed
  apt: pkg=python-librdf state=present

# Application setup

- name: ensure project python packages are installed
  pip: requirements={{ app.root }}/requirements.txt virtualenv={{ app.root }}/venv

- name: ensure honcho is installed
  pip: name=honcho

# - name: create .env configuration file
#   template: ???
